const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const {JSDOM}=require('jsdom');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 // Probe returns immediately while loading, and selects the requested exact track.
 const d=new JSDOM('<input value="https://www.youtube.com/watch?v=k1M9SsaKvfs"><div class="layout align-center"><button class="download-button" data-title="[RAW] English (United States) (auto-generated)">RAW</button></div><div class="layout align-center"><button class="download-button" data-title="[RAW] Thai (auto-generated)">RAW</button></div>',{url:'https://downsub.com/',runScripts:'outside-only'});
 d.window.eval(fs.readFileSync('extension/downsub.js','utf8'));
 let result=await d.window.readDownsubExport('https://www.youtube.com/watch?v=k1M9SsaKvfs','Thai');assert.equal(result.rawTitle,'[RAW] Thai (auto-generated)');d.window.document.querySelectorAll('button').forEach(b=>b.remove());assert.equal((await d.window.readDownsubExport('https://www.youtube.com/watch?v=k1M9SsaKvfs')).pending,true);d.window.close();
 async function scenario(mode){
  let handler,source={id:1,windowId:10,active:true,url:'https://www.youtube.com/watch?v=k1M9SsaKvfs',title:'English title without Thai'},helper={id:100,url:'https://downsub.com/?url=video',status:mode==='bridge-missing'?'complete':'loading'},clock=0,reloaded=0,helperCreated=false;const removed=[],calls=[],progress=[];
  const fastTimeout=(f,ms)=>setTimeout(()=>{clock+=ms;f()},ms===500?0:ms===85000?5000:20);
  const chrome={permissions:{contains:async options=>{assert.equal(JSON.stringify(options.origins),JSON.stringify(['https://downsub.com/*','https://subtitle.downsub.com/*']));return mode!=='no-permission'}},sidePanel:{setPanelBehavior(){}},runtime:{id:'ext',getManifest:()=>({version:mode==='stale-manifest'?'0.8.3':'0.8.4',content_scripts:mode==='stale-manifest'?[]:[{js:['downsub-bridge.js'],matches:['https://downsub.com/*']}]}),getURL:p=>'chrome-extension://ext/'+p,onMessage:{addListener:f=>handler=f},onConnect:{addListener:f=>{let register;f({name:'assistant-panel',sender:{id:'ext',url:'chrome-extension://ext/panel.html'},onMessage:{addListener:g=>register=g},onDisconnect:{addListener(){}},postMessage:m=>progress.push(m)});register({windowId:10})}}},tabs:{onUpdated:{addListener(){}},onActivated:{addListener(){}},onRemoved:{addListener(){}},get:async id=>id===1?source:helper,create:async options=>{if(helperCreated){reloaded++;helper={...helper,id:100+reloaded,url:options.url,status:options.url.includes('/raw/')||mode==='bridge-missing'?'complete':'loading'};if(mode==='cancel-on-retry')source.url='https://www.youtube.com/watch?v=aaaaaaaaaaa'}helperCreated=true;return helper},remove:async id=>removed.push(id),reload:async()=>{throw Error('reload must not be used')},sendMessage:async(id,m)=>{
   calls.push({target:{tabId:id},...m});
   if(m.type==='downsub:probe'&&m.phase==='entry'){if(mode==='bridge-missing')throw Error('Could not establish connection. Receiving end does not exist.');if(mode==='hung'||(mode==='first-hung'||mode==='cancel-on-retry')&&reloaded===0)return new Promise(()=>{});if(mode==='late'&&clock<44000)return {data:{pending:true}};if(mode==='pending')return {data:{pending:true}};return {data:{language:'Thai',rawTitle:'[RAW] Thai',source:'DownSub'}};}
   if(m.type==='downsub:click'){assert.equal(m.rawTitle,'[RAW] Thai');if(mode==='late')clock+=1000;helper.url='https://subtitle.downsub.com/raw/example/';helper.status='complete';if(mode==='click-hung')return new Promise(()=>{});return {data:true};}
   if(mode==='raw-hung'&&reloaded===0)return new Promise(()=>{});return {data:mode==='late'?null:mode==='service'?'503 Service Unavailable':mode==='wrong-language'?'English only':'สวัสดี first\nlast'};
  }},scripting:{executeScript:async opts=>{calls.push(opts);if(opts.func.name==='readYoutubeCaptionLanguage')return [{result:{languageCode:'th'}}];assert.equal(opts.func.name,'readYoutubeCaptions','DownSub must never depend on executeScript');if(mode==='late')clock+=24000;return [{result:mode==='pending'||mode==='bridge-missing'?{error:'No native subtitles'}:{text:'native complete',source:'YouTube'}}];}}};
  const ctx={chrome,importScripts(){},URL,Error,Map,Set,AbortController,Date:{now:()=>clock},setTimeout:fastTimeout,clearTimeout,setInterval,clearInterval,readDownsubExport:async function readDownsubExport(){},readYoutubeCaptions:async function readYoutubeCaptions(){},readYoutubeCaptionLanguage:function readYoutubeCaptionLanguage(){}};
  vm.runInNewContext(fs.readFileSync('extension/background.js','utf8'),ctx);
  result=await new Promise(r=>handler({type:'captions',tabId:1,url:source.url,requestId:'cap'},{id:'ext',url:'chrome-extension://ext/panel.html'},r));
  if(mode==='no-permission'){assert.match(result.error,/Chrome 未允许扩展访问 DownSub/);assert.equal(calls.length,0);assert.equal(removed.length,0);return;}
  if(mode==='stale-manifest'){assert.match(result.error,/当前加载的是 0.8.3/);assert.equal(removed.length,0);assert.equal(calls.length,0);return;}
  if(mode==='bridge-missing'){assert.match(result.error,/页面脚本未启动（0.8.4）/);assert(clock<12000,'missing static bridge fails after one fresh helper rather than 45s empty wait');}
  assert.deepEqual(removed,reloaded?[100,101]:[100]);assert(progress.some(m=>m.type==='assistant:caption-progress'&&m.requestId==='cap'));
  if(mode==='loading'){assert.equal(result.data.text,'สวัสดี first\nlast');assert.equal(reloaded,0);const first=calls.find(c=>c.type==='downsub:probe');assert.equal(first.videoUrl,source.url);assert.equal(first.languageCode,'th');}
  if(mode==='first-hung'||mode==='click-hung'){assert.equal(result.data.text,'สวัสดี first\nlast');assert(!calls.some(c=>c.func?.name==='readYoutubeCaptions'));if(mode==='first-hung'){assert.equal(reloaded,1);assert.deepEqual(calls.filter(c=>c.type==='downsub:probe'&&c.phase==='entry').map(c=>c.target.tabId),[100,101]);assert.equal(calls.find(c=>c.type==='downsub:click').target.tabId,101);}}
  if(mode==='cancel-on-retry'){assert.match(result.error,/视频已切换/);assert(!calls.some(c=>c.func?.name==='readYoutubeCaptions'));}
  if(mode==='raw-hung'){assert.equal(result.data.text,'สวัสดี first\nlast');assert.equal(reloaded,1);assert.equal(calls.filter(c=>c.type==='downsub:click').length,1);assert.equal(calls.at(-1).target.tabId,101);assert(!calls.some(c=>c.func?.name==='readYoutubeCaptions'));}
  if(mode==='wrong-language'){assert.equal(result.data.text,'native complete');assert.match(result.data.downsubError,/不是泰语字幕/);}
  if(mode==='service'){assert.equal(result.data.text,'native complete');assert(result.data.downsubError.includes('返回错误'));}
  if(mode==='hung'){assert.equal(result.data.text,'native complete');assert(result.data.downsubError.includes('超时'));assert.equal(reloaded,1);assert.equal(calls.filter(c=>c.type==='downsub:probe'&&c.phase==='entry').length,2,'only one pending injection per document');}
  if(mode==='late'){assert.equal(result.data.text,'native complete');assert(clock<85000,'native fallback retains its full time budget');}
  if(mode==='pending'){assert(result.error.includes('字幕提取失败'));assert.equal(reloaded,1);}
 }
 await scenario('loading');await scenario('hung');await scenario('pending');await scenario('late');await scenario('service');await scenario('first-hung');await scenario('click-hung');await scenario('cancel-on-retry');await scenario('raw-hung');await scenario('wrong-language');await scenario('stale-manifest');await scenario('bridge-missing');await scenario('no-permission');
 // Lost captions response must unlock the panel and cancel only that captions request.
 const p=new JSDOM(fs.readFileSync('extension/panel.html','utf8'),{url:'https://local.test',runScripts:'outside-only'}),w=p.window;const messages=[];let receive;
 const original=w.setTimeout.bind(w);w.setTimeout=(fn,ms)=>original(fn,ms===90000?20:ms);
 w.chrome={tabs:{query:async()=>[{id:1,windowId:10,url:'https://www.youtube.com/watch?v=k1M9SsaKvfs'}],onActivated:{addListener(){}},onUpdated:{addListener(){}}},runtime:{id:'ext',connect:()=>({postMessage(){},disconnect(){},onMessage:{addListener:f=>receive=f}}),onMessage:{addListener(){}},sendMessage:async m=>{messages.push(m);if(m.type==='extract')return {data:{tabId:1,url:'https://www.youtube.com/watch?v=k1M9SsaKvfs',title:'Video',type:'youtube'}};if(m.type==='assistant:context')return {data:{hasTranscript:false}};if(m.type==='captions')return new Promise(()=>{});return {ok:true}}}};
 w.eval(fs.readFileSync('extension/panel.js','utf8'));await pause(10);w.document.getElementById('summary').click();await pause(5);const cap=messages.find(m=>m.type==='captions');receive({type:'assistant:caption-progress',requestId:cap.requestId,sourceUrl:cap.url,text:'正在读取全文…'});assert.equal(w.document.getElementById('status').textContent,'正在读取全文…');await pause(30);assert(w.document.getElementById('status').textContent.includes('超时'));assert.equal(w.document.getElementById('summary').disabled,false);assert(messages.some(m=>m.type==='captions:cancel'&&m.requestId===cap.requestId));assert(!messages.some(m=>m.type==='assistant'));w.close();
 console.log('PASS caption wait: usable controls read while status=loading; synchronous pending probes; exact Thai track; hung injection bounded/fallback; one replacement tab only; helper closes; lost reply unlocks panel/cancels captions only; no empty GPT sends');
})().catch(e=>{console.error(e);process.exitCode=1});
